// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYFBVd7qozfaQ2xyhTON1tVazAxRdV2o',
    appId: '1:480857308305:web:802100d002b28178245330',
    messagingSenderId: '480857308305',
    projectId: 'town-team-96276',
    authDomain: 'town-team-96276.firebaseapp.com',
    storageBucket: 'town-team-96276.firebasestorage.app',
    measurementId: 'G-H4NJMDY4K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEgzvoCK2EaLjjekBJMDe7OeNlOGNGtE',
    appId: '1:480857308305:android:dd23bf2811ba0211245330',
    messagingSenderId: '480857308305',
    projectId: 'town-team-96276',
    storageBucket: 'town-team-96276.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATZHjj5CmGQM8lRDeJJE4wqamAJNc_fxY',
    appId: '1:480857308305:ios:147ae69a8e7ebb1c245330',
    messagingSenderId: '480857308305',
    projectId: 'town-team-96276',
    storageBucket: 'town-team-96276.firebasestorage.app',
    iosBundleId: 'com.example.townteamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATZHjj5CmGQM8lRDeJJE4wqamAJNc_fxY',
    appId: '1:480857308305:ios:147ae69a8e7ebb1c245330',
    messagingSenderId: '480857308305',
    projectId: 'town-team-96276',
    storageBucket: 'town-team-96276.firebasestorage.app',
    iosBundleId: 'com.example.townteamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMYFBVd7qozfaQ2xyhTON1tVazAxRdV2o',
    appId: '1:480857308305:web:b134722abe4dedac245330',
    messagingSenderId: '480857308305',
    projectId: 'town-team-96276',
    authDomain: 'town-team-96276.firebaseapp.com',
    storageBucket: 'town-team-96276.firebasestorage.app',
    measurementId: 'G-RSN5C4CJB0',
  );
}
